# 1. Setup and Paths

This notebook prepares a manageable subset of the Wellington Camera Traps dataset for wildlife classification and predator early-warning experiments.

The raw dataset is kept unchanged under `data/raw/`. Selected metadata and extracted images will be written to `data/interim/` and `data/processed/`.

In [2]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent

RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"
INTERIM_DATA_DIR = PROJECT_ROOT / "data" / "interim"
PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"

CSV_PATH = RAW_DATA_DIR / "wellington_camera_traps.csv"
JSON_PATH = RAW_DATA_DIR / "wellington_camera_traps.json"

# Large archive stored outside the repository
ZIP_PATH = Path(r"D:\download\wct_images.zip")

INTERIM_DATA_DIR.mkdir(parents=True, exist_ok=True)
PROCESSED_DATA_DIR.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("CSV exists:", CSV_PATH.exists())
print("JSON exists:", JSON_PATH.exists())
print("ZIP exists:", ZIP_PATH.exists())

Project root: e:\Code\ai-predator-early-warning
CSV exists: True
JSON exists: True
ZIP exists: True

# 2. Load Metadata

The CSV metadata contains one row per camera-trap image, including the filename, label, site, date, and camera information.

In [3]:
df = pd.read_csv(CSV_PATH)

print("Dataset shape:", df.shape)
print("Columns:", df.columns.tolist())

df.head()

Dataset shape: (270450, 7)
Columns: ['sequence', 'image_sequence', 'file', 'label', 'site', 'date', 'camera']

,sequence,image_sequence,file,label,site,date,camera
0,2,image1,290716114012001a1116.jpg,BIRD,001a,7/29/2016 11:40,111
1,12,image1,100816090812001a1111.jpg,BIRD,001a,8/10/2016 9:08,111
2,17,image1,180516121622001a1602.jpg,BIRD,001a,5/18/2016 12:16,160
3,18,image1,260416120224001a1601.jpg,BIRD,001a,4/26/2016 12:02,160
4,20,image1,160516023810001a1606.jpg,CAT,001a,5/16/2016 2:38,160

In [4]:
label_counts = df["label"].value_counts()

label_counts

label
BIRD              154525
NOTHINGHERE        45721
CAT                30285
HEDGEHOG           10706
MOUSE               6481
RABBIT              5714
POSSUM              4351
UNCLASSIFIABLE      3484
Ship rat            3183
RAT                 2757
DOG                  998
Norway rat           861
GOAT                 645
DEER                 312
HARE                 207
PIG                  193
MUSTELID              27
Name: count, dtype: int64

In [5]:
site_counts = (
    df.groupby("label")["site"]
    .nunique()
    .sort_values(ascending=False)
)

site_counts

label
BIRD              213
NOTHINGHERE       207
CAT               187
UNCLASSIFIABLE    180
HEDGEHOG          161
MOUSE             129
RAT               110
POSSUM             80
RABBIT             61
Ship rat           53
DOG                46
Norway rat         23
HARE               22
GOAT                7
PIG                 7
MUSTELID            6
DEER                6
Name: site, dtype: int64

In [6]:
label_summary = pd.DataFrame({
    "images": label_counts,
    "sites": site_counts
}).fillna(0).astype(int)

label_summary

                images  sites
label
BIRD            154525    213
CAT              30285    187
DEER               312      6
DOG                998     46
GOAT               645      7
HARE               207     22
HEDGEHOG         10706    161
MOUSE             6481    129
MUSTELID            27      6
NOTHINGHERE      45721    207
Norway rat         861     23
PIG                193      7
POSSUM            4351     80
RABBIT            5714     61
RAT               2757    110
Ship rat          3183     53
UNCLASSIFIABLE    3484    180